### ISSUE TITLE
Does this return coordinates when the user selects a location?

### ISSUE THREAD

**Issue by kaneschutzman** [pespantelis/vue-location-picker#1]
Is this already a feature and you just aren't displaying it in the demo?

**Comment by pespantelis** [comment]
Hey @kaneschutzman, thanks for the interest!

Already it returns an `object` with the located place and you can access it only if you set the [2-way binding variable `place`](https://github.com/pespantelis/vue-location-picker#usage).

> - If the marker is moved, returns an [`PlaceResult`](https://developers.google.com/maps/documentation/javascript/places#place_details_responses) object
> - If a place had selected by the autocomplete, returns the first object of [`GeocoderResult`](https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingResults) if it exists, otherwise `null`

You could get the **coordinates** like this:

``` js
var coordinates = place.geometry.location
```

Also, it is shown in the demo just above the `Location Picker` title. :)
