### ISSUE TITLE
Failed to resolve directive: el & Failed to resolve directive: ref

### ISSUE THREAD

**Issue by asepmaulanaismail** [pespantelis/vue-location-picker#5]
i have followed usage instructions on Readme.md and i've got this:

```
[Vue warn]: Failed to resolve directive: el
(found in <LocationPicker> at node_modules\vue-location-picker\src\LocationPicker.vue)

[Vue warn]: Failed to resolve directive: ref
(found in <LocationPicker> at node_modules\vue-location-picker\src\LocationPicker.vue)
```
can someone help me? 
what should i do?

**Comment by estebancores** [comment]
I'm having same problem, @asepmaulanaismail did you found something?

**Comment by asepmaulanaismail** [comment]
> I'm having same problem, @asepmaulanaismail did you found something?

I didn't find something to solve this, so I made my own.
you can find it here: [vue-location-picker.vue](https://gist.github.com/asepmaulanaismail/1e1a87c2bc7339a75e6d1f2745edf07f)
